### ISSUE TITLE
errors uploading ino file on micro

### ISSUE THREAD

**Issue by ccomincini** [vazhure/gSender-Joystick#1]
Hi thank you for sharing your project.
I'm trying to upload the info file on a micro pro board but these erors are blocking me and I do not understand the problem. can u help please?

> gSenderJoystick/gSenderJoystick.ino:8:1: error: 'Joystick_' does not name a type; did you mean 'Joystick'?
>  Joystick_ Joystick(JOYSTICK_DEFAULT_REPORT_ID, JOYSTICK_TYPE_GAMEPAD,
>  ^~~~~~~~~
>  Joystick
> gSenderJoystick/gSenderJoystick.ino: In function 'void setup()':
> gSenderJoystick/gSenderJoystick.ino:38:11: error: expected unqualified-id before '.' token
>    Joystick.begin();
>            ^
> gSenderJoystick/gSenderJoystick.ino: In function 'void loop()':
> gSenderJoystick/gSenderJoystick.ino:85:13: error: expected unqualified-id before '.' token
>      Joystick.setButton(0, bEnabled ? encBtn > 0 : 0);
>              ^
> gSenderJoystick/gSenderJoystick.ino:86:13: error: expected unqualified-id before '.' token
>      Joystick.setButton(1, bEnabled ? fast > 0 : 0);
>              ^
> gSenderJoystick/gSenderJoystick.ino:87:13: error: expected unqualified-id before '.' token
>      Joystick.setButton(2, bEnabled ? nrm > 0 : 0);
>              ^
> gSenderJoystick/gSenderJoystick.ino:88:13: error: expected unqualified-id before '.' token
>      Joystick.setButton(3, bEnabled ? prec > 0 : 0);
>              ^
> gSenderJoystick/gSenderJoystick.ino:99:13: error: expected unqualified-id before '.' token
>      Joystick.setButton(4, (bEnabled && (mode == NONE)) ? plus > 0 : 0);
>              ^
> gSenderJoystick/gSenderJoystick.ino:100:13: error: expected unqualified-id before '.' token
>      Joystick.setButton(5, (bEnabled && (mode == NONE)) ? minus > 0 : 0);
>              ^
> gSenderJoystick/gSenderJoystick.ino:101:13: error: expected unqualified-id before '.' token
>      Joystick.setButton(6, (bEnabled && (mode == XAXIS)) ? plus > 0 : 0);
>              ^
> gSenderJoystick/gSenderJoystick.ino:102:13: error: expected unqualified-id before '.' token
>      Joystick.setButton(7, (bEnabled && (mode == XAXIS)) ? minus > 0 : 0);
>              ^
> gSenderJoystick/gSenderJoystick.ino:103:13: error: expected unqualified-id before '.' token
>      Joystick.setButton(8, (bEnabled && (mode == YAXIS)) ? plus > 0 : 0);
>              ^
> gSenderJoystick/gSenderJoystick.ino:104:13: error: expected unqualified-id before '.' token
>      Joystick.setButton(9, (bEnabled && (mode == YAXIS)) ? minus > 0 : 0);
>              ^
> gSenderJoystick/gSenderJoystick.ino:105:13: error: expected unqualified-id before '.' token
>      Joystick.setButton(10, (bEnabled && (mode == ZAXIS)) ? plus > 0 : 0);
>              ^
> gSenderJoystick/gSenderJoystick.ino:106:13: error: expected unqualified-id before '.' token
>      Joystick.setButton(11, (bEnabled && (mode == ZAXIS)) ? minus > 0 : 0);
>              ^
> gSenderJoystick/gSenderJoystick.ino:107:13: error: expected unqualified-id before '.' token
>      Joystick.setButton(12, (bEnabled && (mode == AAXIS)) ? plus > 0 : 0);
>              ^
> gSenderJoystick/gSenderJoystick.ino:108:13: error: expected unqualified-id before '.' token
>      Joystick.setButton(13, (bEnabled && (mode == AAXIS)) ? minus > 0 : 0);
>              ^
> gSenderJoystick/gSenderJoystick.ino:116:17: error: expected unqualified-id before '.' token
>          Joystick.setButton(t, 0);
>                  ^
> gSenderJoystick/gSenderJoystick.ino:120:15: error: expected unqualified-id before '.' token
>        Joystick.setButton(14, HIGH);
>                ^
> gSenderJoystick/gSenderJoystick.ino:122:15: error: expected unqualified-id before '.' token
>        Joystick.setButton(14, LOW);
>                ^
> 
> exit status 1
> 
> Compilation error: 'Joystick_' does not name a type; did you mean 'Joystick'?
>

**Comment by vazhure** [comment]
put  https://github.com/vazhure/gSender-Joystick/tree/main/Libraries/ArduinoJoystickLibrary
to Documents\Arduino\libraries\

**Comment by ccomincini** [comment]
Good!  thanks a lot
